artifacts_root: artifacts

 
data_ingestion:
  root_dir: artifacts/data_ingestion
  local_data_src: C:/Users/pj/dog-breed-identification.zip
  local_data_file: artifacts/data_ingestion/dog-breed-identification.zip
  unzip_dir: artifacts/data_ingestion
  